# cloudbuild.yaml

steps:
# This is the single, original step to SSH and deploy.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'compute'
    - 'ssh'
    # --- VM Details ---
    - '--zone=us-central1-c'
    - 'eakravtsov@discord-bot-vm'
    # --- Remote Command to Execute on the VM ---
    - '--command'
    - >-
        cd /opt/apps/discord-bot && sudo git fetch --all && sudo git reset --hard origin/computeEngineVersion && sudo chown -R discordbot:discordbot . && sudo -u discordbot /opt/apps/discord-bot/venv/bin/pip install -r requirements.txt && sudo systemctl restart discord-bot.service

# --- The required logging option ---
options:
  logging: CLOUD_LOGGING_ONLY